name: CI
on:
  push:

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: run-tests.sh
        run: ./run-tests.sh

  build-n-push:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: production
      url: https://thermo.alanen.dev
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: ./deploy.sh
