name: CI
on:
  push:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shards: [1, 2, 3, 4, 5]
        total_shards: [5]
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: run-tests.sh
        env:
          PLAYWRIGHT_SHARD: ${{ matrix.shards }}
          PLAYWRIGHT_TOTAL_SHARDS: ${{ matrix.total_shards }}
        run: ./run-tests.sh
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.shards }}
          path: test-results

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
      url: https://thermo.alanen.dev
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: ./deploy.sh
